# Generated by Django 3.1.5 on 2021-05-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorador', '0003_auto_20210510_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
