# Generated by Django 3.1.5 on 2021-06-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorador', '0004_dados_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.CharField(max_length=100)),
            ],
        ),
    ]
